### ISSUE TITLE
Contour Orders

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/DancingScript#1]
@richardlipton 

Cycle through and visually check all glyphs before syncing and notification. 

Check that contour order and start points are correct.

e.g /won  /percent  /perthousand

<img width="326" alt="DancingScript contour order 2019-10-22 at 7 49 40 PM" src="https://user-images.githubusercontent.com/6576107/67344620-89adfa00-f506-11e9-8c03-514a2d3ce548.png">

<img width="106" alt="DancingScript contour order 2019-10-22 at 7 50 09 PM" src="https://user-images.githubusercontent.com/6576107/67344621-89adfa00-f506-11e9-9a6e-8fdd93526b43.png">

**Comment by richardlipton** [comment]
Fixes completed.
