### ISSUE TITLE
GF QA

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/DancingScript#3]
Very good overall. Only issue I found are collapsed double stacking marks.

![mkmk](https://user-images.githubusercontent.com/7525512/68085466-470aec80-fe39-11e9-8a14-9e255aabd683.gif)

**Comment by cjdunn** [comment]
@m4rc1e The differences shown seem to be for strings like: /circumflexcomb /tildecomb 

The actually stacking accents seem to be fine in the sources. For example /acircumflextilde is referencing /circumflexcomb_tildecomb which is not collapsed (see image below)

![stacking_accents_not_collapsed](https://user-images.githubusercontent.com/3900241/68148437-fe6f3400-ff09-11e9-81a4-573c7bafd149.png)

Is the difference above just from generating in different software? Is there a real world use case where this would come up? I'm not sure how to fix these if they do indeed need fixing, please advise.

**Comment by m4rc1e** [comment]
> Is the difference above just from generating in different software? 

No. Same issue on Win.

>  Is there a real world use case where this would come up?

They're used in Vietnamese, https://vietnamesetypography.com/alphabet/

Since the sources have the glyphs, the reason why they're not shaping must be the input. You can use `hb-shape` to check how the input is being processed. If I check the fonts on GF we get:

```
hb-shape /Users/marcfoley/Downloads/Dancing_Script/DancingScript-Regular.ttf  "̂̉"
[uni0302=0+0|hookabovecomb=0@0,175+0]

```



If I check the VF, I get:

```
hb-shape /Users/marcfoley/Type/upstream_families/DancingScript/fonts/vf/DancingScript\[wght\].ttf "̂̉" --features="ccmp"
[uni0302=0+0|hookabovecomb=0+0]
```

Neither seem to be shaping to the ligature glyphs (my hb-shape commands may need to be more thorough). However, we can see that the static is atleast being positioned above the caron.

If I were in your shoes, I'd regen the OT features to see if that solves it.

**Comment by cjdunn** [comment]
Fixed via this PR:
https://github.com/TypeNetwork/DancingScript/pull/4
